name: mini_fluency
description: "A mini learning path app for English lessons - Fluency Academy"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^6.1.0
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.4
  google_fonts: ^6.2.1
  json_annotation: ^4.9.0
  package_info_plus: ^8.1.1
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.13
  derry: ^1.5.0
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/data/
    - assets/images/
    - assets/images/logos/
    - assets/audio/

scripts: derry.yaml
